### ISSUE TITLE
sql file

### ISSUE THREAD

**Issue by ahmadsolehin** [hendisantika/spring-boot-datatable#1]
hello mas,, can u attach sql file also?

**Comment by hendisantika** [comment]
Sorry @ahmadsolehin  baru nyadar ternyata ada yg merhatikan reponya dan create issue.

SQL nya itu otomatis diinisialisasi pas bootstrap app nya. Jadi anda tidak perlu import datanya. Karena itu otomatis saya setting d Main App nya sebagai bean.

**Comment by hendisantika** [comment]
Sudah solved ya mas @ahmadsolehin .
